In [63]:
import numpy as np
from IPython.display import display

In [64]:
# Quiz 1 : 맨 가장자리는 모두 0, 내부는 모두 1인 10 by 10 행렬을 구하여라.
X = np.zeros((10, 10))
X[1:9, 1:9] = 1
X

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [65]:
# Quiz 2 : 행렬 A, B에 대하여 ((A + B) X (-A / 2 )) 를 in place (without copy)로 계산
# -9~9까지의 정수 중 4개를 임의로 선택하여 2x2 행렬 2개 생성 (A, B)
random_generator = np.random.RandomState(42)
A = random_generator.randint(-9, 10, 4).reshape((2, 2))
B = random_generator.randint(-9, 10, 4).reshape((2, 2))
C = np.zeros((2, 2))
display(A)
display(B)
# A, B에 대한 연산 시행 (여기서 x 연산은 dot으로 계산)
display(np.add(A, B))
display(np.divide(-A, 2))
np.dot(np.add(A, B), np.divide(-A, 2), out=C)
display(C)

array([[-3,  5],
       [ 1, -2]])

array([[-3,  9],
       [ 1,  1]])

array([[-6, 14],
       [ 2, -1]])

array([[ 1.5, -2.5],
       [-0.5,  1. ]])

array([[-16. ,  29. ],
       [  3.5,  -6. ]])

In [66]:
# Quiz 3 : 3개의 배열이 주어졌을 때 아래 조건에 따라 새롭게 생성되는 배열을 구하시오.
# cond[i]가 true이면 xarr[i]를 선택
# cond[i]가 false이면 yarr[i]를 선택
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
np.where(cond, xarr, yarr)

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [67]:
# Quiz 4 : 크기가 11인 배열이 다음과 같이 주어졌을 때, 5번째 원소부터 9번째 원소까지를 음수로 바꾸어 보시오.
# given Array
quiz4Arr = np.arange(11)
# processing
np.multiply(quiz4Arr[5:10], -1, out=quiz4Arr[5:10])
quiz4Arr

array([ 0,  1,  2,  3,  4, -5, -6, -7, -8, -9, 10])

In [68]:
# Quiz 5 : 난수생성기를 사용하여 크기가 0부터 9까지의 숫자로 구성된, 크기가 20인 배열을 생성하고, 배열의 최대값을 0으로 만들어라.
